
name: Lint (pylint)

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint $(git ls-files "*.py")
